### PR TITLE
Increase the timeout value for service start/stop

### LINKED ISSUE #1766: vShared plugin: volume mount failed due to cannot start service before timeout
Steps:
1. create a volume with vShared plugin
```
root@sc-rdops-vm02-dhcp-52-237:~# docker volume create --driver=vshared --name=vol1
vol1
root@sc-rdops-vm02-dhcp-52-237:~# docker volume inspect vol1
[
    {
        "Driver": "vshared:latest",
        "Labels": {},
        "Mountpoint": "/mnt/vshared/vol1/",
        "Name": "vol1",
        "Options": {},
        "Scope": "global",
        "Status": {
            "Clients": null,
            "File server Port": 0,
            "Global Refcount": 0,
            "Service name": "",
            "Volume Status": "Ready"
        }
    }
]

```
2. run a container to attach this volume
```
root@sc-rdops-vm02-dhcp-52-237:~# docker run -it -v vol1:/vol busybox /bin/sh
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
9e87eff13613: Pull complete 
Digest: sha256:2605a2c4875ce5eb27a9f7403263190cd1af31e48a2044d400320548356251c4
Status: Downloaded newer image for busybox:latest
docker: Error response from daemon: error while mounting volume '/mnt/vshared/vol1/': VolumeDriver.Mount: Failed to blocking wait for Mounted state. Error: Timeout reached; BlockingWait is not complete..

root@sc-rdops-vm02-dhcp-52-237:~# docker volume inspect vol1
[
    {
        "Driver": "vshared:latest",
        "Labels": {},
        "Mountpoint": "/mnt/vshared/vol1/",
        "Name": "vol1",
        "Options": {},
        "Scope": "global",
        "Status": {
            "Clients": null,
            "File server Port": 0,
            "Global Refcount": 0,
            "Service name": "",
            "Volume Status": "Error"
        }
    }
]

```

This is the vsphere_shared.log:
```
2017-08-16 15:37:34.151414591 -0700 PDT [INFO] VolumeDriver Get: vol1
2017-08-16 15:37:34.183235052 -0700 PDT [INFO] Volume not found: vol1
2017-08-16 15:37:34.184316907 -0700 PDT [ERROR] Failed to get volume meta-data error="No such volume" name=vol1 
2017-08-16 15:37:34.185197406 -0700 PDT [INFO] VolumeDriver Create: vol1
2017-08-16 15:37:34.185492167 -0700 PDT [INFO] Attempting to write initial metadata entry for vol1
2017-08-16 15:37:34.205793526 -0700 PDT [INFO] Watcher on global refcount returns event type=PUT 
2017-08-16 15:37:34.206888201 -0700 PDT [INFO] Attempting to create internal volume for vol1
2017-08-16 15:37:39.513496693 -0700 PDT [INFO] Attempting to update volume state to ready for volume: vol1
2017-08-16 15:37:39.594893479 -0700 PDT [INFO] Successfully created volume: vol1
2017-08-16 15:37:47.723957447 -0700 PDT [INFO] VolumeDriver Get: vol1
2017-08-16 15:38:01.259606622 -0700 PDT [INFO] VolumeDriver Get: vol1
2017-08-16 15:38:01.532861749 -0700 PDT [INFO] Mounting volume name=vol1 
2017-08-16 15:38:01.533706618 -0700 PDT [INFO] Directory doesn't exist, creating it path="/mnt/vshared/vol1/" 
2017-08-16 15:38:01.533827245 -0700 PDT [INFO] Before AtomicIncr
2017-08-16 15:38:02.599618816 -0700 PDT [INFO] Watcher on global refcount returns event type=PUT 
2017-08-16 15:38:03.600109932 -0700 PDT [INFO] Attempting to change volume state to Mounting
2017-08-16 15:38:10.304162321 -0700 PDT [INFO] Checking status of file server container...
2017-08-16 15:38:10.318087448 -0700 PDT [INFO] File server not running for volume vol1
2017-08-16 15:38:15.30415672 -0700 PDT [INFO] Checking status of file server container...
2017-08-16 15:38:15.308395133 -0700 PDT [INFO] File server not running for volume vol1
2017-08-16 15:38:20.304441888 -0700 PDT [INFO] Checking status of file server container...
2017-08-16 15:38:20.308937468 -0700 PDT [INFO] File server not running for volume vol1
2017-08-16 15:38:25.30413009 -0700 PDT [INFO] Checking status of file server container...
2017-08-16 15:38:25.307482481 -0700 PDT [INFO] File server not running for volume vol1
2017-08-16 15:38:30.304159117 -0700 PDT [INFO] Checking status of file server container...
2017-08-16 15:38:30.307000833 -0700 PDT [INFO] File server not running for volume vol1
2017-08-16 15:38:35.304201001 -0700 PDT [INFO] Checking status of file server container...
2017-08-16 15:38:35.30726231 -0700 PDT [INFO] File server not running for volume vol1
2017-08-16 15:38:35.307351514 -0700 PDT [WARNING] Timeout reached while waiting for file server container for volume vol1
2017-08-16 15:38:43.715999508 -0700 PDT [INFO] Watcher on global refcount returns event type=PUT 
2017-08-16 15:38:43.716619966 -0700 PDT [ERROR] name=vol1 error="Failed to blocking wait for Mounted state. Error: Timeout reached; BlockingWait is not complete." 
2017-08-16 15:38:43.716865852 -0700 PDT [ERROR] Failed to mount name=vol1 error="Failed to blocking wait for Mounted state. Error: Timeout reached; BlockingWait is not complete." 
```

docker service takes longer time than expected to start.
```
root@sc-rdops-vm02-dhcp-52-237:~# docker service ls
ID            NAME            MODE        REPLICAS  IMAGE
zlzxbqm0s728  vol1fileServer  replicated  0/1       dperson/samba:latest
root@sc-rdops-vm02-dhcp-52-237:~# docker service ps vol1fileServer 
ID            NAME                  IMAGE                 NODE                       DESIRED STATE  CURRENT STATE             ERROR                             PORTS
kbihay4nds7k  vol1fileServer.1      dperson/samba:latest  sc-rdops-vm02-dhcp-52-237  Running        Preparing 14 seconds ago                                    
kca4wdczcpp2   \_ vol1fileServer.1  dperson/samba:latest  sc-rdops-vm02-dhcp-52-237  Shutdown       Rejected 15 seconds ago   "No such image: dperson/samba@…"  
root@sc-rdops-vm02-dhcp-52-237:~# docker service ls
ID            NAME            MODE        REPLICAS  IMAGE
zlzxbqm0s728  vol1fileServer  replicated  1/1       dperson/samba:latest

```

### PR DESCRIPTION
**Pull request by lipingxue**
Fixes #1766 
This PR includes: 
Increase the timeout value when waiting for Samba service to start/stop and also the timeout value for block waiting.

The Swarm samba service can take up to 1.5 minutes to come up on setup with less resource, so set the timeout value for waiting for Samba service to start/stop to 90 seconds, and set the timeout value for block waiting for 120 seconds.

### CODE REVIEW

**Comment by lipingxue** [comment]
@msterin This will happen one the first mount to a volume created by shared plugin.  The first mount request need to start a swarm service to run Samba server,  and the mount need to wait until samba server start successfully. In some setup,  it takes up to 90 seconds for the Samba server to come up. With a smaller timeout value (40 seconds before this change),  the first mount failed since samba service cannot start before it times out.

**Comment by lipingxue** [comment]
@msterin What do you mean set this as a plugin option? You mean user need to specify the value when installed the plugin?

**Comment by msterin** [comment]
yes, plugin option is similar to "--config" in config.json for vDVS plugin. You can add "--service-start-timeout 120" there. 

on the "why" - what takes 60 sec ? Sounds WAY too slow. Is it because of creating a new volume the very first time, and the need to format it ? Can you check in ESX logs what takes time ?

**Comment by shivanshu21** [comment]
BTW this sloth is only observable on nimbus VMs which are resource starved. My local VMs are able to mount the volume for the first time in 9 seconds.

The subsequent mounts on the same node are almost instantaneous.

**Comment by luomiao** [comment]
Even on the testbed I got from nimbus, it won't take that long :)
But previous when I tried another script which deploys testbed with very limited resource, it will hit the timeout.
So it's very platform dependent.

@lipingxue 
Can you add the change to userguide to add this new config flag information when you update the PR?

**Comment by msterin** [comment]
> But previous when I tried another script which deploys testbed with very limited resource, it will hit the timeout. So it's very platform dependent.

And this exactly my point. We should (1) understand which steps is taking all that time when resource are low   (2) NOT set timeout for extreme cases. but instead make it reasonable and provide a config

**Comment by lipingxue** [comment]
@msterin 
Hi Mark, I have added an option to config the timeout value when installing the plugin(I introduced an env variable VFILE_TIMEOUT_IN_SECOND for this):
```
root@sc-rdops-vm02-dhcp-52-237:~# docker plugin install --grant-all-permissions --alias vshared lipingxue/vsphere-shared:vshared-unmount1 VFILE_TIMEOUT_IN_SECOND=90
vshared-unmount1: Pulling from lipingxue/vsphere-shared
bb2a72c3caa5: Download complete 
Digest: sha256:21e762a406a6dc31202a93e52ae6893b61e1d9adeb515564859ba477bb1564cc
Status: Downloaded newer image for lipingxue/vsphere-shared:vshared-unmount1
Installed plugin lipingxue/vsphere-shared:vshared-unmount1
```
In the log, we can see the timeout value we used is the value from config variable
```
2017-08-23 11:08:51.919778216 -0700 PDT [INFO] Get sambaRequest timeout from config 
 value=90
```

**Comment by lipingxue** [comment]
@msterin @luomiao I have addressed your comments, and please review it.

**Comment by luomiao** [comment]
LGTM

File: client_plugin/drivers/shared/dockerops/dockerops.go [hunk 1]
```diff
@@ -65,14 +66,44 @@ const (
...
+	isSambaRequestTimeoutSet bool = false
+)
+
+// return SambaRequest timeout value
+func GetSambaRequestTimeout() time.Duration {
+	if isSambaRequestTimeoutSet != false {
+		return SambaRequestTimeout
+	}
+	// read sambaRequest Timout value from enviroment variable
+	timeOutFromConfig := os.Getenv("VFILE_TIMEOUT_IN_SECOND")
```
Comment (msterin) [inline client_plugin/drivers/shared/dockerops/dockerops.go]: I do not think there is a need for `isSambaRequestTimeoutSet `.
This should make do, won't it ? 
 
```go
func GetSambaRequestTimeout() time.Duration {
 timeOutSec, err := strconv.Atoi(os.Getenv("VFILE_TIMEOUT_IN_SECOND"))
 if err != nil {
   timeOutSec = defaultSambaRequestTimeOutInSecond 
 }
  log.WithFields(log.Fields{"value": timeOutSec ,}).Info("sambaRequest timeout")
  return time.Duration(timeOutSec ) * time.Second
}
```

  
Also, this hjas nothing to do with Samba, it is a generic timeout for service start. Please rename accordingly

File: client_plugin/drivers/shared/dockerops/dockerops.go [hunk 2]
```diff
@@ -65,14 +66,24 @@ const (
 	checkDuration = 5 * time.Second
 	// Time between successive checks for deleting a volume
 	checkSleepDuration = time.Second
-	// Timeout to mark Samba service launch as unsuccessful
-	sambaRequestTimeout = 30 * time.Second
+	// default Timeout to mark Samba service launch as unsuccessful
+	defaultServiceStartTimeOutInSecond = 30
```
Comment (msterin) [inline client_plugin/drivers/shared/dockerops/dockerops.go]: nit: slightly shorter name (e.g. _defaultSvcStartTimeoutSec_ or even _defaultStartTimeout_ with comment) would be nice.

File: docs/user-guide/vfile-plugin.md [hunk 3]
```diff
@@ -3,14 +3,14 @@ title: vFile volume plugin for Docker
 
 ---
 ## Overview
-Depending on the underlying block storage device system, it might not be possible to access the same 
+Depending on the underlying block storage device system, it might not be possible to access the same
```
Comment (msterin) [inline docs/user-guide/vfile-plugin.md]: `block device`  or `block storage system`, not both

File: docs/user-guide/vfile-plugin.md [hunk 4]
```diff
@@ -124,3 +124,11 @@ docker service create --replicas 1 -p 8080:80 --name web nginx
 ```
 Then on each host, make sure there is valid return of `curl 127.0.0.1:8080`.
 `Connection refused` error means the routing mesh of this Docker Swarm cluster is broken and needs to be fixed.
+
+### I got " VolumeDriver.Mount: Failed to blocking wait for Mounted state. Error: Timeout reached; BlockingWait is not complete.." when mounting a volume.
+We see this issue only on platforms which the availble disk space are low. On those platforms, docker swarm service takes longer time to up and running. We recommend to run this driver on platforms with enough available disk space. You can also try to increase the service start timeout value by specifing ```VFILE_TIMEOUT_IN_SECOND``` value when installing the plugin:
```
Comment (msterin) [inline docs/user-guide/vfile-plugin.md]: Suggestion: 

When  available disk space are low, Docker Swarm service may take longer start a service. Generally it's better free up some e disk space. You can also try to increase the service start timeout value, controlled by ```VFILE_TIMEOUT_IN_SECOND``` env variable:

File: docs/user-guide/vfile-plugin.md [hunk 5]
```diff
@@ -124,3 +124,11 @@ docker service create --replicas 1 -p 8080:80 --name web nginx
...
+```
+docker plugin install --grant-all-permissions --alias vfile cnastorage/vfile:latest VFILE_TIMEOUT_IN_SECOND=90
+```
+The above command increases the service start timeout value to 90 seconds and the default value is 30 seconds.
```
Comment (msterin) [inline docs/user-guide/vfile-plugin.md]: This will increase timeout to 90 sec, from default of 30 sec

File: docs/user-guide/vfile-plugin.md (hunk 3 above)
Comment (lipingxue) [inline docs/user-guide/vfile-plugin.md]: Done.

File: docs/user-guide/vfile-plugin.md (hunk 4 above)
Comment (lipingxue) [inline docs/user-guide/vfile-plugin.md]: Done.

Comment (lipingxue) [inline docs/user-guide/vfile-plugin.md]: Done.

File: docs/user-guide/vfile-plugin.md (hunk 5 above)
Comment (lipingxue) [inline docs/user-guide/vfile-plugin.md]: Done.
