### PR TITLE
Fix error handling when rolling back volume creation

### LINKED ISSUE #616: Plugin client must print an error message in case of create error
Recent changes to formatting of the disks on the guest side may have introduced this error. When create hits an error condition we get this,

root@photon-jyLxAJ3OK [ ~ ]# docker volume create -d vmdk --name v2
Error response from daemon: create v2: Post http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: ContentLength=24 with Body length 0

### PR DESCRIPTION
**Pull request by brunotm**
Fixes #616

### CODE REVIEW

File: vmdk_plugin/plugin.go [hunk 1]
```diff
@@ -249,10 +249,10 @@ func (d *vmdkDriver) Create(r volume.Request) volume.Response {
...
 		log.WithFields(log.Fields{"name": r.Name,
 			"error": err}).Error("Attach volume failed, removing the volume ")
-		err = d.ops.Remove(r.Name, nil)
-		if err != nil {
-			log.WithFields(log.Fields{"name": r.Name, "error": err}).Error("Remove volume failed ")
-			return volume.Response{Err: err.Error()}
+		errRm := d.ops.Remove(r.Name, nil)
+		if errRm != nil {
+			log.WithFields(log.Fields{"name": r.Name, "error": errRm}).Error("Remove volume failed ")
+			return volume.Response{Err: errRm.Error()}
```
Comment (govint) [inline vmdk_plugin/plugin.go]: Its preferable that the error returned on a create error is the create error itself vs. a remove error (which is confusing to the user). OTOH, how did this cause the empty response from docker to the docker command line.

Comment (brunotm) [inline vmdk_plugin/plugin.go]: >Its preferable that the error returned on a create error is the create error itself vs. a remove error (which is confusing to the user, when they issued a create command). 

Agree.

>OTOH, how did this cause the empty response from docker to the docker command line. 

err was being reassigned to nil inside the rollback block after the attach error, and at the end we would return the volume response with an error nil since we didn't got any errors from the rollback operations. Which if we had, in any case we would return from there.

Tests in plugin.go:

line 248   //dev, err := d.ops.Attach(r.Name, nil)
line 249   err = fmt.Errorf("STUB")
line 250   dev := []byte("an")

**Without the patch:**
root@vsc01:/tmp/docker-volume-vsphere# docker volume create -d vmdk --name vol$$ -o size=1gb
Error response from daemon: create vol25407: Post http://%2Frun%2Fdocker%2Fplugins%2Fvmdk.sock/VolumeDriver.Create: http: ContentLength=78 with Body length 0

**in log:**
2016-10-08 21:32:38.880136128 +0100 WEST [INFO] Attaching volume and creating filesystem fstype=ext4 name=vol25407
2016-10-08 21:32:38.880268068 +0100 WEST [ERROR] Attach volume failed, removing the volume error=STUB name=vol25407

**With the patch:**
root@vsc01:/tmp/docker-volume-vsphere# docker volume create -d vmdk --name vol$$ -o size=1gb
Error response from daemon: create vol25407: VolumeDriver.Create: STUB

**in log:**
2016-10-08 21:37:47.746007178 +0100 WEST [INFO] Attaching volume and creating filesystem name=vol25407 fstype=ext4
2016-10-08 21:37:47.746070732 +0100 WEST [ERROR] Attach volume failed, removing the volume name=vol25407 error=STUB

**Comment by brunotm** [comment]
@govint
I have updated the commit to address your comment about returning from the main error.

File: vmdk_plugin/plugin.go [hunk 2]
```diff
@@ -249,10 +249,9 @@ func (d *vmdkDriver) Create(r volume.Request) volume.Response {
 	if err != nil {
 		log.WithFields(log.Fields{"name": r.Name,
 			"error": err}).Error("Attach volume failed, removing the volume ")
-		err = d.ops.Remove(r.Name, nil)
-		if err != nil {
-			log.WithFields(log.Fields{"name": r.Name, "error": err}).Error("Remove volume failed ")
-			return volume.Response{Err: err.Error()}
+		errRm := d.ops.Remove(r.Name, nil)
+		if errRm != nil {
+			log.WithFields(log.Fields{"name": r.Name, "error": errRm}).Error("Remove volume failed ")
```
Comment (msterin) [inline vmdk_plugin/plugin.go]: Warning(). Failed to remove here is not necessarily a big issue I think.

File: vmdk_plugin/plugin.go [hunk 3]
```diff
@@ -261,15 +260,13 @@ func (d *vmdkDriver) Create(r volume.Request) volume.Response {
 	if err != nil {
 		log.WithFields(log.Fields{"name": r.Name,
 			"error": err}).Error("Could not find attached device, removing the volume ")
-		err = d.ops.Detach(r.Name, nil)
-		if err != nil {
-			log.WithFields(log.Fields{"name": r.Name, "error": err}).Error("Detach volume failed ")
-			return volume.Response{Err: err.Error()}
+		errDetach := d.ops.Detach(r.Name, nil)
```
Comment (msterin) [inline vmdk_plugin/plugin.go]: should not it be errInGetPath , following the pattern of err<where> names ?

File: vmdk_plugin/plugin.go [hunk 4]
```diff
@@ -278,15 +275,13 @@ func (d *vmdkDriver) Create(r volume.Request) volume.Response {
 	if err != nil {
 		log.WithFields(log.Fields{"name": r.Name,
 			"error": err}).Error("Create filesystem failed, removing the volume ")
-		err = d.ops.Detach(r.Name, nil)
-		if err != nil {
-			log.WithFields(log.Fields{"name": r.Name, "error": err}).Error("Detach volume failed ")
-			return volume.Response{Err: err.Error()}
+		errDetach := d.ops.Detach(r.Name, nil)
```
Comment (msterin) [inline vmdk_plugin/plugin.go]: errMkfs

File: vmdk_plugin/plugin.go (hunk 2 above)
Comment (brunotm) [inline vmdk_plugin/plugin.go]: And about other operations in rollback? Should we also log with warning? IMO those are subsequent errors.

**Comment by brunotm** [comment]
@msterin 
I have updated the PR, it actually makes more sense to only log as Error the original issue.

File: vmdk_plugin/plugin.go (hunk 2 above)
Comment (msterin) [inline vmdk_plugin/plugin.go]: Yes. I think errors on rollback are generally warnings - like it's helpful to warn if something we expected to complete failed, but it does not impact success/failure of the actual operation requested.  We can silently ignore but I am generally not comfortable with silent failures.

File: vmdk_plugin/plugin.go [hunk 5]
```diff
@@ -235,66 +235,61 @@ func (d *vmdkDriver) Create(r volume.Request) volume.Response {
...
-	if err != nil {
+	errMkfs := fs.Mkfs(mkfscmd, r.Name, device)
+	if errMkfs != nil {
 		log.WithFields(log.Fields{"name": r.Name,
-			"error": err}).Error("Create filesystem failed, removing the volume ")
-		err = d.ops.Detach(r.Name, nil)
-		if err != nil {
-			log.WithFields(log.Fields{"name": r.Name, "error": err}).Error("Detach volume failed ")
-			return volume.Response{Err: err.Error()}
+			"error": errMkfs}).Error("Create filesystem failed, removing the volume ")
```
Comment (msterin) [inline vmdk_plugin/plugin.go]: looks like detach/remove has to be separate in a function instead of copy-paste.

**Comment by brunotm** [comment]
@msterin 
If it would reutilized beyond these 2 cases, i wouldn't mind.
But this PR would be the place for it?

**Comment by msterin** [comment]
@brunotm - for this PR it's not a problem, I am just generally sensitive to copy-n-paste :-). 
At any rate, since we have 2 approved I am merging the PR. Thanks !
