### PR TITLE
Recover attached volumes after a VM reset or VM migrating after ESX host down.

### LINKED ISSUE #1675: Volume stays attached if the ESX of the vm goes down and vsphere HA moves vm to different ESX
Test Steps:
```
1. Created a volume.
2. Ran a container with volume mounted and wrote data to it.
3. Turned on vsphere HA.
4. While container is running, powered-off the esx on which vm resides. 
5. vSphere HA power-off's the vm and restarts it on a different ESX.
6. After vm successfully comes back up, volume shows up as 'attached' even though there are no containers running.
Also volume removal fails with error: Volume is in use.
```

Logs have been attached at the end.

-------------------------------------------

Steps and their output are as follows:

1. Created a volume.
```
root@sc-rdops-vm02-dhcp-52-237:~# docker volume create -d vsphere:latest --name TestVol
TestVol
root@sc-rdops-vm02-dhcp-52-237:~#
root@sc-rdops-vm02-dhcp-52-237:~# docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      TestVol@sharedVmfs-0
root@sc-rdops-vm02-dhcp-52-237:~# docker volume inspect TestVol@sharedVmfs-0
[
    {
        "Driver": "vsphere:latest",
        "Labels": null,
        "Mountpoint": "/mnt/vmdk/TestVol@sharedVmfs-0",
        "Name": "TestVol@sharedVmfs-0",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": "13MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Tue Aug  1 19:10:53 2017",
            "created by VM": "ubuntu-VM0.1",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "detached"
        }
    }
]
root@sc-rdops-vm02-dhcp-52-237:~#

[root@sc-rdops-vm01-dhcp-0-74:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py volume ls
Volume   Datastore     VMGroup   Capacity  Used  Filesystem  Policy  Disk Format  Attached-to  Access      Attach-as               Created By    Created Date
-------  ------------  --------  --------  ----  ----------  ------  -----------  -----------  ----------  ----------------------  ------------  ------------------------
TestVol  sharedVmfs-0  _DEFAULT  100MB     13MB  ext4        N/A     thin         detached     read-write  independent_persistent  ubuntu-VM0.1  Tue Aug  1 19:10:53 2017

[root@sc-rdops-vm01-dhcp-0-74:~]
```
2. Turned on vSphere HA.

3. Ran the container with volume mounted and then wrote the data to it.
```
root@sc-rdops-vm02-dhcp-52-237:~#  docker run -it --volume-driver=vsphere:latest -v TestVol@sharedVmfs-0:/vol1 --name ubHA ubuntu
root@c4dacf722bf7:/#
root@c4dacf722bf7:/# ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  vol1
root@c4dacf722bf7:/#
root@c4dacf722bf7:/# echo "Hello" > vol1/hello
root@c4dacf722bf7:/# cat vol1/hello
Hello
root@c4dacf722bf7:/#
root@c4dacf722bf7:/# echo "World" >> vol1/hello
root@c4dacf722bf7:/# cat vol1/hello
Hello
World
root@c4dacf722bf7:/#
```
4. Admin cli volume ls also shows volume as attached.
```
[root@sc-rdops-vm01-dhcp-0-74:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py volume ls
Volume   Datastore     VMGroup   Capacity  Used  Filesystem  Policy  Disk Format  Attached-to   Access      Attach-as               Created By    Created Date
-------  ------------  --------  --------  ----  ----------  ------  -----------  ------------  ----------  ----------------------  ------------  ------------------------
TestVol  sharedVmfs-0  _DEFAULT  100MB     15MB  ext4        N/A     thin         ubuntu-VM0.1  read-write  independent_persistent  ubuntu-VM0.1  Tue Aug  1 19:10:53 2017

[root@sc-rdops-vm01-dhcp-0-74:~]
```
5. Now while the container is running, shut-down the esx.

6. vSphere HA powers-off and restarts the docker host on a different ESX .

7. After vm has successfully restarted on different ESX, I do see the original volume -  TestVol@sharedVmfs-0
```
root@sc-rdops-vm02-dhcp-52-237:~# docker volume ls
DRIVER              VOLUME NAME
vsphere:latest      TestVol@sharedVmfs-0
root@sc-rdops-vm02-dhcp-52-237:~#
root@sc-rdops-vm02-dhcp-52-237:~# docker volume inspect TestVol@sharedVmfs-0
[
    {
        "Driver": "vsphere:latest",
        "Labels": null,
        "Mountpoint": "/mnt/vmdk/TestVol@sharedVmfs-0",
        "Name": "TestVol@sharedVmfs-0",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "attached to VM": "ubuntu-VM0.1",
            "attachedVMDevice": {
                "ControllerPciSlotNumber": "160",
                "Unit": "0"
            },
            "capacity": {
                "allocated": "15MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Tue Aug  1 19:10:53 2017",
            "created by VM": "ubuntu-VM0.1",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "attached"
        }
    }
]
root@sc-rdops-vm02-dhcp-52-237:~#
root@sc-rdops-vm02-dhcp-52-237:~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@sc-rdops-vm02-dhcp-52-237:~#
root@sc-rdops-vm02-dhcp-52-237:~# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                            PORTS               NA                                                             MES
c4dacf722bf7        ubuntu              "/bin/bash"         11 minutes ago      Exited (255) About a minute ago                       ub                                                             HA
root@sc-rdops-vm02-dhcp-52-237:~#
```
8. Admin cli volume ls
```
[root@sc-rdops-vm01-dhcp-18-68:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py volume ls
Volume   Datastore     VMGroup   Capacity  Used  Filesystem  Policy  Disk Format  Attached-to   Access      Attach-as               Created By    Created Date
-------  ------------  --------  --------  ----  ----------  ------  -----------  ------------  ----------  ----------------------  ------------  ------------------------
TestVol  sharedVmfs-0  _DEFAULT  100MB     15MB  ext4        N/A     thin         ubuntu-VM0.1  read-write  independent_persistent  ubuntu-VM0.1  Tue Aug  1 19:10:53 2017

[root@sc-rdops-vm01-dhcp-18-68:~]
```

9. Removed the container but volume still shows-up as attached. Hence not able to remove volume and we have a left-over volume.
```
root@sc-rdops-vm02-dhcp-52-237:~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@sc-rdops-vm02-dhcp-52-237:~#
root@sc-rdops-vm02-dhcp-52-237:~# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                       PORTS               NAMES
c4dacf722bf7        ubuntu              "/bin/bash"         16 minutes ago      Exited (255) 6 minutes ago                       ubHA
root@sc-rdops-vm02-dhcp-52-237:~#
root@sc-rdops-vm02-dhcp-52-237:~# docker rm c4dacf722bf7
c4dacf722bf7
root@sc-rdops-vm02-dhcp-52-237:~#
root@sc-rdops-vm02-dhcp-52-237:~# docker volume inspect TestVol@sharedVmfs-0
[
    {
        "Driver": "vsphere:latest",
        "Labels": null,
        "Mountpoint": "/mnt/vmdk/TestVol@sharedVmfs-0",
        "Name": "TestVol@sharedVmfs-0",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "attached to VM": "ubuntu-VM0.1",
            "attachedVMDevice": {
                "ControllerPciSlotNumber": "160",
                "Unit": "0"
            },
            "capacity": {
                "allocated": "15MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Tue Aug  1 19:10:53 2017",
            "created by VM": "ubuntu-VM0.1",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "attached"     <<<<<<<<<<<<<<<<<<<<<<<<<
        }
    }
]
root@sc-rdops-vm02-dhcp-52-237:~#
root@sc-rdops-vm02-dhcp-52-237:~# docker volume rm TestVol@sharedVmfs-0
Error response from daemon: unable to remove volume: remove TestVol@sharedVmfs-0: VolumeDriver.Remove: Failed to remove volume TestVol, in use by VM = ubuntu-VM0.1.
root@sc-rdops-vm02-dhcp-52-237:~#
```

Logs:
[docker.txt](https://github.com/vmware/docker-volume-vsphere/files/1191804/docker.txt)
[docker-volume-vsphere.txt](https://github.com/vmware/docker-volume-vsphere/files/1191803/docker-volume-vsphere.txt)
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/1191805/vmdk_ops.txt)

### PR DESCRIPTION
**Pull request by govint**
Fixes #1675 and #1638 

Added a refcount recovery time detach of volumes that aren't used by any containers in the VM but attached to the VM. Also added a test to verify volume is detached once a VM restarts after reset.

For now using the volume name entries under the mount root used by the plugin vs. requesting the service to get the volumes attached to the VM. Can cause an issue if the VM is reset during a create op. But that needs more changes and can be taken up later.

Tested on Linux only for now, will need to get a Windows set up for testing.

Testing reset of VM and volume recovery :
```
docker volume inspect snapvol2
[
    {
        "Driver": "vsphere",
        "Labels": {},
        "Mountpoint": "/mnt/vmdk/snapvol2",
        "Name": "snapvol2",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": "15MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Sun Aug  6 13:01:34 2017",
            "created by VM": "worker1-VM1.0",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "detached"
        }
    }
]

govc vm.power -reset=true master-VM0.0
Reset VirtualMachine:1... OK

docker volume inspect snapvol2
[
    {
        "Driver": "vsphere",
        "Labels": {},
        "Mountpoint": "/mnt/vmdk/snapvol2",
        "Name": "snapvol2",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "attached to VM": "master-VM0.0",
            "attachedVMDevice": {
                "ControllerPciSlotNumber": "160",
                "Unit": "0"
            },
            "capacity": {
                "allocated": "15MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Sun Aug  6 13:01:34 2017",
            "created by VM": "worker1-VM1.0",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "attached"
        }
    }
]
```
Still reports attached as target VM hasn't powered back on yet.
```
docker volume inspect snapvol2
[
    {
        "Driver": "vsphere",
        "Labels": {},
        "Mountpoint": "/mnt/vmdk/snapvol2",
        "Name": "snapvol2",
        "Options": {},
        "Scope": "global",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": "15MB",
                "size": "100MB"
            },
            "clone-from": "None",
            "created": "Sun Aug  6 13:01:34 2017",
            "created by VM": "worker1-VM1.0",
            "datastore": "sharedVmfs-0",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "detached"
        }
    }
]
```
Plugin logs,
Before reset:
```
2017-08-07 13:10:55.699825821 +0000 UTC [INFO] Going into ServeUnix - Listening on Unix socket address="/run/docker/plugins/vsphere.sock"
2017-08-07 13:11:44.087982216 +0000 UTC [INFO] Mounting volume name=snapvol2
2017-08-07 13:11:44.175170393 +0000 UTC [INFO] volume name=snapvol2@sharedVmfs-0 refcnt=1
2017-08-07 13:11:44.175887082 +0000 UTC [INFO] Successfully retrieved mountsmap=map[]
2017-08-07 13:11:44.1759302 +0000 UTC [INFO] Directory doesn't exist, creating it path="/mnt/vmdk/snapvol2@sharedVmfs-0"
2017-08-07 13:11:45.306466477 +0000 UTC [INFO] Scan complete device="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0" event="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0": 0x100 == IN_CREATE
2017-08-07 13:11:45.539629322 +0000 UTC [INFO] Unmounting Volume name=snapvol2
2017-08-07 13:11:45.539665661 +0000 UTC [INFO] volume name=snapvol2@sharedVmfs-0 refcnt=0
2017-08-07 13:11:46.170043123 +0000 UTC [INFO] Mounting volume name=snapvol2
2017-08-07 13:11:46.236550318 +0000 UTC [INFO] volume name=snapvol2@sharedVmfs-0 refcnt=1
2017-08-07 13:11:46.236836908 +0000 UTC [INFO] Successfully retrieved mountsmap=map[]
2017-08-07 13:11:47.106325179 +0000 UTC [INFO] Scan complete event="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0": 0x100 == IN_CREATE device="/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0"
```

After reset:
```
2017-08-07 13:15:34.233861727 +0000 UTC [INFO] No config file found. Using defaults.
2017-08-07 13:15:34.237091638 +0000 UTC [INFO] Starting plugin driver=vsphere log_level=info config="/etc/docker-volume-vsphere.conf"
2017-08-07 13:15:34.237122697 +0000 UTC [INFO] Getting volume data from unix:///var/run/docker.sock
2017-08-07 13:15:34.268053571 +0000 UTC [INFO] Found 0 running or paused containers
2017-08-07 13:15:34.268411605 +0000 UTC [INFO] Successfully retrieved mountsmap=map[]
2017-08-07 13:15:34.271584541 +0000 UTC [ERROR] Failed to unmount volume. Now trying to detach... mountpoint="/mnt/vmdk/snapvol2@sharedVmfs-0" error="Unmount device at /mnt/vmdk/snapvol2@sharedVmfs-0 failed: invalid argument" <---------- volume is detached here

2017-08-07 13:15:34.647849591 +0000 UTC [INFO] Discovered 1 volumes that may be in use.
2017-08-07 13:15:34.647938971 +0000 UTC [INFO] Refcounting successfully completed
2017-08-07 13:15:34.647960071 +0000 UTC [INFO] Docker VMDK plugin started version="vSphere Volume Driver v0.5" port=1019 mock_esx=false
2017-08-07 13:15:34.64832532 +0000 UTC [INFO] Going into ServeUnix - Listening on Unix socket address="/run/docker/plugins/vsphere.sock"
```

### CODE REVIEW

File: client_plugin/utils/refcount/refcnt.go [hunk 1]
```diff
@@ -508,5 +520,17 @@ func (r *RefCountsMap) updateRefMap() error {
...
+	// Add volumes found under mountRoot, reset refMap entry
+	// for those that are present under mountRoot but aren't
+	// mounted.
+	volumes, err := fs.GetMountRootEntries(mountRoot)
+	if err != nil {
+		return err
+	}
+	for _, vol := range volumes {
+		if _, ok := r.refMap[vol]; ok == false {
+			r.refMap[vol] = nil
```
Comment (pdhamdhere) [inline client_plugin/utils/refcount/refcnt.go]: I dont remember all refCnt datastructures OTOH. However, this looks inconsistent with overall logic.Why not keep refInfo entry and use refInfo.mounted= false or introduce new field to distinguish volume is attached but not mounted.

File: client_plugin/utils/refcount/refcnt.go [hunk 2]
```diff
@@ -428,6 +430,16 @@ func (r *RefCountsMap) syncMountsWithRefCounters(d drivers.VolumeDriver) {
 	defer r.mtx.Unlock()
 
 	for vol, cnt := range r.refMap {
+		// If cnt is nil then this volume entry under mount root can be
+		// purged and the volume detached (if it is attached).
+		if cnt == nil {
```
Comment (pdhamdhere) [inline client_plugin/utils/refcount/refcnt.go]: See my comment below. Rather than depending on NULL entry, we should switch-case based on mounted | refCnt | something else?

Comment (govint) [inline client_plugin/utils/refcount/refcnt.go]: Yes, I didn't want to allocate mem. for the refCount structs for these entries and hence left them as empty entries. Can do it eitherway, allocate the structs and mark those as mounted = false and then remove them. Another thing is i'm using UnmountVolume() when clearly these volumes aren't mounted, I'll add a Detach() to the Drivers interface so the unmount error doesn't show up in the logs.

Comment (govint) [inline client_plugin/utils/refcount/refcnt.go]: CI run failed as tthe plugin hasn't yet detached the volume when the test code verified the detached state. BUt the plugin logs show that the volume was detached.

File: client_plugin/utils/refcount/refcnt.go (hunk 1 above)
Comment (govint) [inline client_plugin/utils/refcount/refcnt.go]: Fixed.

File: client_plugin/utils/refcount/refcnt.go [hunk 3]
```diff
@@ -447,10 +449,15 @@ func (r *RefCountsMap) syncMountsWithRefCounters(d drivers.VolumeDriver) {
...
-				// volume unmounted AND refcount 0.  We should NEVER get here
-				// since unmounted and recount==0 volumes should have no record
-				// in the map. Something went seriously wrong in the code.
-				log.WithFields(f).Panic("Internal failure: record should not exist. ")
+				// This volume may be attached to the VM but not mounted as no containers
+				// are using it. A detach is attempted and the entry under the mount root is
+				// removed.
+				err := d.DetachVolume(vol)
+				if err != nil {
+					log.Warning("Failed to detach %s - manual recovery may be needed", vol)
```
Comment (pshahzeb) [inline client_plugin/utils/refcount/refcnt.go]: We can be more specific here as to what admin needs to do. Something like  "Manually detaching the disk may be needed"

File: client_plugin/utils/refcount/refcnt.go [hunk 4]
```diff
@@ -447,10 +449,15 @@ func (r *RefCountsMap) syncMountsWithRefCounters(d drivers.VolumeDriver) {
...
+				}
+				fs.Rmdir(strings.Join([]string{mountRoot, vol}, "/"))
```
Comment (pshahzeb) [inline client_plugin/utils/refcount/refcnt.go]: If this op wasn't around till date, how were the entries from mountRoot removed?

In such a case, there will be entries under mountRoot even for the volumes that have been successfully detached.
Due to updateRefMap() reading this entries, they ll be populated in refMap.
An attempt to detach them would fail (since they were already detached before).
We ll end up flagging false warning for such cases through line 457.

Comment (govint) [inline client_plugin/utils/refcount/refcnt.go]: With this change going forward /mnt/vmdk will be cleaned up. Any installation of the vmdk driver will have /mnt/vmdk full of directories that may have been used at some time.  The warning message really will be a once only when the plugin is updated and a host already has some entries under /mnt/vmdk not thereafter.

File: client_plugin/utils/refcount/refcnt.go (hunk 3 above)
Comment (govint) [inline client_plugin/utils/refcount/refcnt.go]: That could be a release note for the user to check and detach disks  and otherwise ignore the once only warning.

File: client_plugin/utils/refcount/refcnt.go (hunk 4 above)
Comment (pshahzeb) [inline client_plugin/utils/refcount/refcnt.go]: > The warning message really will be a once only when the plugin is updated and a host already has some entries under /mnt/vmdk not thereafter.

Yes. But it will be for most of the installations since many of them have existing volumes.

Maybe a release note will help here.

File: tests/e2e/vmops_test.go [hunk 5]
```diff
@@ -146,3 +146,33 @@ func (vm *VMOpsTest) TestVMSnapWithIndependentDisk(c *C) {
...
+	// 3. Reset the VM
+	out = esx.ResetVM(vm.config.DockerHostNames[0])
+
+	// 4. Verify VM gets back to powered-on state
+	isVDVSRunning := esx.IsVDVSRunningAfterVMRestart(vm.config.DockerHosts[0], vm.config.DockerHostNames[0])
+	c.Assert(isVDVSRunning, Equals, true, Commentf("vDVS is not running after VM [%s] being restarted", vm.volName1))
+
+	// 5. Verify volume is detached
+	// Give time for the plugin to complete its recovery
+	misc.SleepForSec(10)
```
Comment (pshahzeb) [inline tests/e2e/vmops_test.go]: This time can't be accurately predicted. PollDetachedStatus instead of VerifyDetachedStatus is an alternative and we can get rid of the sleep.

Comment (govint) [inline tests/e2e/vmops_test.go]: You're right and it should be PollDetachedStatus(). The refcount recovery is unfortunately itself not bounded as from a couple of the CI failures the recovery keeps retrying and takes longer. I'll change this to use polling.

**Comment by govint** [comment]
CI green with polled detach status. Let me know if any more comments, else will merge this one.
