### PR TITLE
Various test fixes to maintain CI stability

### LINKED ISSUE #1302: [CI] deployESXInstall failed during CI run
**CI run:** https://ci.vmware.run/vmware/docker-volume-vsphere/263

**Error:**
```
Connection to 192.168.31.62 closed by remote host.\r
Installation Result:
  Message: Operation finished successfully.
  Reboot Required: false
  VIBs Installed: VMWare_bootbank_esx-vmdkops-service_0.14.cbfebd6-0.0.1
  VIBs Removed: 
  VIBs Skipped: 


=> deployESXInstall: Installation hit an error on root@192.168.31.62 Fri May 26 09:23:08 UTC 2017



make[1]: *** [deploy-esx] Error 2
make: *** [deploy-esx] Error 2
=> Build + Test not successful Fri May 26 09:23:08 UTC 2017

```

**hostd.log:**

```
2017-05-26T09:22:33.352Z info hostd[2D305B70] [Originator@6876 sub=Solo.Vmomi opID=4bf76fc8 user=dcui:dvolplug] Throw vmodl.fault.RequestCanceled
2017-05-26T09:22:33.353Z info hostd[2D305B70] [Originator@6876 sub=Solo.Vmomi opID=4bf76fc8 user=dcui:dvolplug] Result:
--> (vmodl.fault.RequestCanceled) {
-->    faultCause = (vmodl.MethodFault) null,
-->    faultMessage = <unset>
-->    msg = ""
--> }

```

### LINKED ISSUE #1308: vmlistener_test tearDown logic is unstable
vmlistener_test tearDown logic is unstable: it fails intermittently when I run e2e test locally:

2017/05/30 18:28:55 Failed to invoke command [docker volume rm vmlistener_test_volume_1496168883]: exit status 1

----------------------------------------------------------------------
FAIL: vmlistener_test.go:61: VMListenerTestParams.TearDownTest

vmlistener_test.go:67:
    c.Assert(err, IsNil, Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc420167620), Stderr:[]uint8(nil)} ("exit status 1")
... Error response from daemon: unable to remove volume: remove vmlistener_test_volume_1496168883: VolumeDriver.Remove: Remove failure - volume is still mounted.  volume=vmlistener_test_volume_1496168883, refcount=1

----------------------------------------------------------------------
PANIC: vmlistener_test.go:80: VMListenerTestParams.TestKillVM

... Panic: Fixture has panicked (see related PANIC)
OOPS: 8 passed, 1 FAILED, 1 MISSED
--- FAIL: Test (274.17s)

### PR DESCRIPTION
**Pull request by shuklanirdesh82**
This PR focuses on following things

- fixes #1308 - Supplying increased wait time for fixing vmlistener cleanup method
- Fixing installation script to install vDVS plugin onto swarm worker2 node (/CC @shaominchen )
- fixes #1302 - resolving deployESXInstall failure during CI run

### CODE REVIEW

File: tests/utils/misc/misc.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ func WaitForExpectedState(fn getVMPowerStatus, vmName, expectedState string) boo
 
 	log.Printf("Confirming [%s] power status for vm [%s]\n", expectedState, vmName)
 	for attempt := 0; attempt < maxAttempt; attempt++ {
-		SleepForSec(3)
+		SleepForSec(5)
```
Comment (govint) [inline tests/utils/misc/misc.go]: Make as constant in this file? And say double the sleep in each iteration?

Comment (shuklanirdesh82) [inline tests/utils/misc/misc.go]: Sure @govint  I will move out as const ... but will keep the same value instead of increasing to reduce the time .. we are expecting this operation to be finished sooner. 

Please let me know if there is any advantage for increasing exponentially.

**Comment by shuklanirdesh82** [comment]
CI is failing and blocked due to `VIB installation issue` .. I will update the PR with fresh changes.

**Comment by shuklanirdesh82** [comment]
CI is passing and back to stable

- https://ci.vmware.run/vmware/docker-volume-vsphere/301
- https://ci.vmware.run/vmware/docker-volume-vsphere/303
