### PR TITLE
attach / detach delta disks handling fix

### LINKED ISSUE #554: Delta disks prevent attaching an already-attached volume
if a volume is a part of VM snapshot and is represented by a delta disk, an attempt to attach it again fails. 

To reproduce:
create a persistent volume, use it, then take a VM snapshot , kill the container using the volume, and try to use the volume again. 
* Guest:  `docker volume create -d vmdk --name=vol -o attach_as=persistent; docker run --name test -d -v vol:/v  busybox ping 8.8.8.8`
* host: snapshot the VM , e.g. `vim-cmd vmsvc/snapshot.create 2 snap no no`
* guest: `docker rm -f test  ; docker run --rm -it -v vol:/v busybox`

Result: fails with "cannot attach to scsci:1". Expected: success
Reason: volume->path and back is confused by -0001 in the vmdk name
/cc @pdhamdhere

### PR DESCRIPTION
**Pull request by msterin**
Fixes #554 

When looking for full path of the VMDK representing a docker volume,
take in account (potential) existence of delta disks.
Also made `make` interruptible  when running docker (added '-it') and added a few debug messages

Tested:
* make all, CI
* Manual: followed steps in #554 . all worked
* Manual: created multiple snapshots, erased some , created more (to break numbering sequence), checked docker volume ls  and docker run with the volume - all works (correct filenames are reported in the logs too)

### CODE REVIEW

File: misc/scripts/build.sh [hunk 1]
```diff
@@ -85,7 +85,7 @@ DOCKER="$DEBUG docker"
 
 if [ "$1" == "rpm" ] || [ "$1" == "deb" ]
 then
-  $DOCKER run --rm  \
+  $DOCKER run --rm  -it \
```
Comment (kerneltime) [inline misc/scripts/build.sh]: Why is this needed?

File: misc/scripts/build.sh [hunk 2]
```diff
@@ -96,7 +96,7 @@ then
   $DOCKER run --rm -it -v $PWD/..:$dir -w $dir $go_container bash -c "go get -u github.com/FiloSottile/gvt; bash"
 else
   docker_socket=/var/run/docker.sock
-  $DOCKER run --privileged --rm \
+  $DOCKER run --privileged --rm -it \
```
Comment (kerneltime) [inline misc/scripts/build.sh]: Same here.

File: misc/scripts/build.sh (hunk 1 above)
Comment (msterin) [inline misc/scripts/build.sh]: that allows to kill 'make' with Control-C, instead of waiting for it to compete

File: esx_service/utils/vmdk_utils.py [hunk 3]
```diff
@@ -66,13 +66,27 @@ def get_volumes():
...
+
+    # Get a delta disk list, and if it's empty - return the full path for volume VMDK base file
+    # Note: we rely on NEVER allowing '-' in volume name and on the fact that ESXi
+    # always creates deltadisks as <name>-DDDDDD.vmdk (D is a digit) for delta disks
+    delta_disks = glob.glob("{0}/{1}-*[0-9].vmdk".format(path, vol_name))
+    if not delta_disks:
+        return os.path.join(path, "{0}.vmdk".format(vol_name))
+
+    # this funky code gets the name of the youngest delta disk:
+    latest = sorted([(vmdk, os.stat(vmdk).st_ctime) for vmdk in delta_disks], key=lambda d: d[1], reverse=True)[0][0]
```
Comment (andrewjstone) [inline esx_service/utils/vmdk_utils.py]: Nice functional code. Also +1 for the using the term 'funky' 💃

**Comment by andrewjstone** [comment]
LGTM

File: misc/scripts/build.sh (hunk 1 above)
Comment (kerneltime) [inline misc/scripts/build.sh]: Ok.

**Comment by kerneltime** [comment]
LGTM
