### PR TITLE
Fix issue in build.sh and add more log for vFile.

### LINKED ISSUE #1974: build failed with error
In top of the tree, "make build" failed with the following error
```
lipingx-m01:docker-volume-vsphere lipingx$ make build-all
/Library/Developer/CommandLineTools/usr/bin/make --directory=client_plugin build-all
../misc/scripts/build.sh pylint
make: Entering directory '/go/src/github.com/vmware/docker-volume-vsphere/esx_service'
make: Nothing to be done for 'pylint'.
make: Leaving directory '/go/src/github.com/vmware/docker-volume-vsphere/esx_service'
../misc/scripts/build.sh build
docker: Error response from daemon: invalid bind mount spec "/Users/lipingx/.ssh/id_rsa::ro": invalid volume specification: '/Users/lipingx/.ssh/id_rsa::ro': invalid mount config for type "bind": field Target must not be empty.
See 'docker run --help'.
make[1]: *** [dockerbuild] Error 125
make: *** [build-all] Error 2
```

### PR DESCRIPTION
**Pull request by lipingxue**
Fixed #1974

### CODE REVIEW

File: misc/scripts/build.sh [hunk 1]
```diff
@@ -123,7 +123,7 @@ then
   $DOCKER run --rm  -v $PWD/..:$dir -w $dir $pylint_container $MAKE_ESX pylint
 else
   docker_socket=/var/run/docker.sock
-  if [ -z '$SSH_KEY_OPT' ]
+  if [ -z "$SSH_KEY_OPT" ]
```
Comment (shuklanirdesh82) [inline misc/scripts/build.sh]: we need to add some reference in the contributing.md about when to initialize `SSH_KEY_OPT ` and how does it look like for any contributor to set while using the key which stores on non-default path.

Comment (luomiao) [reply misc/scripts/build.sh]: +1
We need to add one line into the doc about how to set SSH_KEY_OPT.
It needs to be set in the format of:
export SSH_KEY_OPT='-i /Users/username/.ssh/id_rsa'
The key point is using '' instead of "".

Comment (lipingxue) [reply misc/scripts/build.sh]: Done.

**Comment by lipingxue** [comment]
@luomiao @shuklanirdesh82 I have addressed your comments, please review it.

File: CONTRIBUTING.md [hunk 2]
```diff
@@ -110,6 +110,11 @@ The prerequisite to build and deploy the plugin is to have a DockerHub account.
 
 - The build will use your `username` (the output of `whoami`) to decide on the `DOCKER_HUB_REPO` name to complete our move to use managed plugin. If you want to use another DockerHub repository you need to set `DOCKER_HUB_REPO` as environment variable.
 
+- You **need** to set enviroment variable `SSH_KEY_OPT` if your ssh keys are not stored in the default location with the following format:
```
Comment (shuklanirdesh82) [inline CONTRIBUTING.md]: nit: `enviroment` => `environment`

Comment (lipingxue) [reply CONTRIBUTING.md]: Done.
